version: '3.7'
services:
  db:
    container_name: di-db
    image: 'postgres:latest'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres

  app:
    container_name: di-app
    build: ./ 
    ports:
      - '3000:3000'
    volumes:
      - .:/docker/app
    depends_on:
      - db

volumes:
  postgres:
