version: '3.7'
services:
  db:
    container_name: di-db
    image: 'postgres:latest'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - di-network

  app:
    container_name: di-app
    build: ./ 
    ports:
      - '3000:3000'
    volumes:
      - .:/docker/app
    depends_on:
      - db
    networks:
      - di-network

  redis:
    container_name: di-redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - di-network

volumes:
  postgres:

networks:
  di-network:
